### ISSUE TITLE
New branch for future version?

### ISSUE THREAD

**Issue by DanielCleemann** [Joschbosch/kickertool#45]
Hi, 

can you create a new branch for the next issues? I can also do it. Would that be version 1.1 then?

**Comment by Joschbosch** [comment]
Since we want to be good devs, I created a TAG for 0.0.1. Also I started a gitflow development branch which would now be for the next version 0.0.2. You can switch to that :)
Also, there is a nice plugin for egit in the eclipse marketplace, which allows you to control the repo with gitflow (start new feature, create release branch....). It's called "GitflowNightly". Maybe you want to try is out :D

**Comment by DanielCleemann** [comment]
Nice! Yeah, I thought we already are at version/tag 1.0.0. :D But maybe not.
